# Generated by Django 6.0.7 on 2026-08-11 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_client_message_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="declarationfiscale",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="declarations",
                to="core.clientservicesuivi",
                verbose_name="Dossier lié",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="dossier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="core.clientservicesuivi",
                verbose_name="Dossier lié",
            ),
        ),
    ]
