# Generated by Django 6.0.7 on 2026-08-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_dossier_explorer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Fonction / Poste"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ajouté le"),
                ),
            ],
            options={
                "verbose_name": "Collaborateur",
                "verbose_name_plural": "Personnel (collaborateurs)",
                "ordering": ["nom", "prenom", "id"],
            },
        ),
        migrations.AddField(
            model_name="servicefollowup",
            name="collaborateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="followups",
                to="core.collaborateur",
                verbose_name="Collaborateur assigné",
            ),
        ),
    ]
